const {chromium}=require('playwright');
const fs=require('fs');
const APP='http://127.0.0.1:8899/';
const out={version:'RC1.4.545',steps:[],posts:[],startedAt:new Date().toISOString()};
let shotNo=0;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function shot(p,name){const f=`rc545-${String(++shotNo).padStart(2,'0')}-${name.replace(/[^\p{L}\p{N}_-]+/gu,'_')}.png`;await p.screenshot({path:f,fullPage:false});return f;}
async function dismiss(p){for(let i=0;i<5;i++){let hit=0;for(const s of ['[data-profile-unlock-close]','#rareBurstCloseBtn','.mike-talk-close','#tutorialCloseBtn','#firstRunCloseBtn','[data-mobile-more-close]']){try{const x=p.locator(s).first();if(await x.count()&&await x.isVisible()){await x.click({timeout:800});hit++;await sleep(100);}}catch{}}if(!hit&&i>1)break;await sleep(250);}}
async function step(p,name,fn){try{await dismiss(p);const detail=await fn();const screenshot=await shot(p,name);out.steps.push({name,ok:true,detail:detail||null,screenshot});console.log('PASS',name,JSON.stringify(detail||{}));return detail;}catch(e){const screenshot=await shot(p,'FAIL-'+name).catch(()=>'');const r={name,ok:false,error:String(e&&e.stack||e),screenshot};out.steps.push(r);console.error('FAIL',name,e);throw e;}}
async function makePage(browser,name,viewport={width:1360,height:900}){const ctx=await browser.newContext({viewport});await ctx.addInitScript(({name})=>{localStorage.setItem('fujiya_mitekore_early_access_v2',JSON.stringify({orderNumber:'99999999',verifiedAt:Date.now(),campaign:'rc545'}));localStorage.setItem('fujiya_collection_setup_done_v1','1');localStorage.setItem('fujiya_collection_tutorial_seen_v2_rc1474','1');localStorage.setItem('fujiya_collection_first_run_seen_v20_2_35cn','1');localStorage.setItem('fujiya_collection_user_name',name);localStorage.setItem('fujiya_collection_share_opt_in_v1','1');},{name});const p=await ctx.newPage();p.setDefaultTimeout(25000);p.on('dialog',d=>d.accept().catch(()=>{}));await p.goto(APP,{waitUntil:'domcontentloaded',timeout:60000});await p.waitForFunction(()=>typeof window.miteHoOpenTab==='function'&&!!window.fujiyaMiteMagazineApi,{timeout:60000});await sleep(5000);await dismiss(p);try{await p.locator('#quickProfileEditBtn').click();await p.locator('#quickUserNameInput').fill(name);await p.locator('#quickSaveUserNameBtn').click();await sleep(1500);await dismiss(p);}catch{}return {ctx,p};}
async function openMiteHo(p){await dismiss(p);await p.evaluate(()=>window.miteHoOpenTab());await p.waitForSelector('#miteHoPanel',{state:'visible',timeout:30000});await sleep(1000);}
async function compose(p,type,comment){await p.locator('[data-miteho-compose]:visible').click();await p.locator('#miteHoComposer:visible').waitFor();await p.locator(`[data-miteho-type="${type}"]:visible`).click();if(comment!==undefined)await p.locator('#miteHoComment:visible').fill(comment);}
async function waitCard(p,text,timeout=110000){await p.waitForFunction(t=>[...document.querySelectorAll('.miteho-card')].some(x=>x.textContent.includes(t)),text,{timeout});return p.locator('.miteho-card:visible').filter({hasText:text}).first();}
async function publishGame(p,comment){await compose(p,'game',comment);await p.waitForFunction(()=>{try{return typeof MASTER_TITLES!=='undefined'&&Array.isArray(MASTER_TITLES)&&MASTER_TITLES.length>100;}catch{return false;}},{timeout:60000});await p.locator('#miteHoGameSearch:visible').fill('ファイアレッド');const choice=p.locator('[data-miteho-game-choice]:visible').filter({hasText:'ファイアレッド'}).first();await choice.waitFor({state:'visible',timeout:20000});await choice.click();await p.locator('#miteHoSubmit:visible').click();const card=await waitCard(p,comment);return card.getAttribute('data-miteho-card');}
async function publishUrl(p,comment){await compose(p,'url',comment);await p.locator('#miteHoUrl:visible').fill('https://example.com/');await p.locator('#miteHoSubmit:visible').click();const card=await waitCard(p,comment);return card.getAttribute('data-miteho-card');}
async function publishPhoto(p,comment,file){await compose(p,'photo',comment);await p.locator('#miteHoPhoto').setInputFiles(file);await p.waitForFunction(()=>document.querySelector('#miteHoPhotoPreview img')?.src?.startsWith('data:image/'),undefined,{timeout:20000});await p.locator('#miteHoSubmit:visible').click();const card=await waitCard(p,comment);return card.getAttribute('data-miteho-card');}
async function main(){
  const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAIAAAACCAIAAAD91JpzAAAAFElEQVR4nGP8z8DAwMDAxMDAwMAAAAwBAQAY3Y2QAAAAAElFTkSuQmCC','base64');
  fs.writeFileSync('rc545-test-photo.png',png);
  const browser=await chromium.launch({headless:true});
  const stamp=Date.now().toString().slice(-8);
  const A=`ChatGPTみてほしいA${stamp}`;
  const B=`ChatGPTみてほしいB${stamp}`;
  const gameComment=`ゲーム投稿テスト${stamp}`;
  const photoComment=`写真投稿テスト${stamp}`;
  const urlComment=`URL投稿テスト${stamp}`;
  const shopComment=`SHOP受信テスト${stamp}`;
  const a=await makePage(browser,A);
  await step(a.p,'545表示・新タブ',async()=>{const title=await a.p.title();const hero=await a.p.locator('.hero-build-version').innerText();const core=await a.p.locator('script[src*="app-core-"]').getAttribute('src');if(!title.includes('RC1.4.545')||hero.trim()!=='RC1.4.545'||!String(core).includes('app-core-545.js'))throw Error('545資産不一致');await openMiteHo(a.p);if(!await a.p.locator('[data-ui-tab="miteho"]:visible').count())throw Error('PCタブなし');return {title,hero,core};});
  await step(a.p,'100文字制限',async()=>{await compose(a.p,'game','あ'.repeat(100));const ta=a.p.locator('#miteHoComment:visible');await ta.press('End');await ta.type('い');const value=await ta.inputValue();const count=await a.p.locator('#miteHoCount').innerText();if(Array.from(value).length!==100||!count.includes('100 / 100'))throw Error(`100文字制限失敗 ${Array.from(value).length} ${count}`);await a.p.locator('[data-miteho-close]:visible').click();return {length:Array.from(value).length,count};});
  const game=await step(a.p,'ゲームをみてコレ',async()=>{const id=await publishGame(a.p,gameComment);out.posts.push(id);const article=await a.p.evaluate(id=>window.fujiyaMiteMagazineApi.read(id),id);if(!article?.tags?.includes('MITEHO')||!article?.tags?.includes('MITEHO_GAME'))throw Error('共有DBタグ不一致');return {id,tags:article.tags,comment:gameComment};});
  const photo=await step(a.p,'写真をみてコレ',async()=>{const id=await publishPhoto(a.p,photoComment,'rc545-test-photo.png');out.posts.push(id);const card=await waitCard(a.p,photoComment);if(!await card.locator('.miteho-card-media img').count())throw Error('写真カード画像なし');const article=await a.p.evaluate(id=>window.fujiyaMiteMagazineApi.read(id),id);if(!String(article?.coverData||'').startsWith('data:image/'))throw Error('共有DB写真なし');return {id,coverLength:String(article.coverData).length};});
  const url=await step(a.p,'URLをみてコレ',async()=>{const id=await publishUrl(a.p,urlComment);out.posts.push(id);const card=await waitCard(a.p,urlComment);const link=card.locator('.miteho-link-card').first();if(!await link.count())throw Error('URLカードなし');return {id,href:await link.getAttribute('href')};});
  const shop=await step(a.p,'SHOP投稿受け口',async()=>{const id=await a.p.evaluate(async({stamp,comment})=>{const userId=window.fujiyaMiteMagazineApi.currentUserId();const a=await window.fujiyaMiteHoCreateShopPost({authorUserId:userId,authorName:'藤や玩具店',authorNickname:'SHOP',productId:`test-${stamp}`,title:'MOTHER2 ギーグの逆襲',platform:'SFC',price:4980,condition:'箱説あり',productUrl:'https://example.com/shop-item',comment});return a.id;},{stamp,comment:shopComment});out.posts.push(id);await a.p.locator('[data-miteho-refresh]:visible').click();const card=await waitCard(a.p,shopComment);const t=await card.innerText();if(!t.includes('藤や玩具店')||!t.includes('4,980円')||!t.includes('商品を見る'))throw Error('SHOP表示不一致 '+t);const art=await a.p.evaluate(id=>window.fujiyaMiteMagazineApi.read(id),id);if(!art?.tags?.includes('MITEHO_SHOP'))throw Error('SHOPタグなし');return {id,tags:art.tags};});
  await step(a.p,'みてマガと分離',async()=>{await a.p.evaluate(()=>window.miteMagazineOpenTab());await a.p.waitForSelector('#miteMagazineFeed',{state:'visible'});await a.p.locator('[data-mag-refresh]:visible').click().catch(()=>{});await sleep(2500);const text=await a.p.locator('#miteMagazineFeed').innerText();for(const c of [gameComment,photoComment,urlComment,shopComment])if(text.includes(c))throw Error('みてマガにMITEHOが混入 '+c);return {separated:true};});
  const b=await makePage(browser,B);
  await step(b.p,'別ユーザーで受信',async()=>{await openMiteHo(b.p);await b.p.locator('[data-miteho-refresh]:visible').click();const card=await waitCard(b.p,gameComment,120000);return {id:await card.getAttribute('data-miteho-card'),author:B,seen:true};});
  await step(b.p,'別ユーザーから♡',async()=>{const card=await waitCard(b.p,gameComment);const like=card.locator('[data-miteho-like]').first();await like.click();await b.p.waitForFunction(id=>{const c=document.querySelector(`[data-miteho-card="${CSS.escape(id)}"]`);return c?.querySelector('[data-miteho-like]')?.textContent.includes('いいね済み');},game.id,{timeout:70000});const article=await b.p.evaluate(id=>window.fujiyaMiteMagazineApi.read(id),game.id);const count=Number(article?.pollResults?.counts?.heart||0);if(count<1||article?.pollResults?.myOptionId!=='heart')throw Error('♡共有DB反映なし');return {count,myOptionId:article.pollResults.myOptionId};});
  await step(a.p,'投稿者側にも♡反映',async()=>{await openMiteHo(a.p);await a.p.locator('[data-miteho-refresh]:visible').click();await waitCard(a.p,gameComment);const article=await a.p.evaluate(id=>window.fujiyaMiteMagazineApi.read(id),game.id);const count=Number(article?.pollResults?.counts?.heart||0);if(count<1)throw Error('投稿者側♡件数なし');const card=a.p.locator(`[data-miteho-card="${game.id}"]`);await card.scrollIntoViewIfNeeded();await a.p.waitForFunction(id=>document.querySelector(`[data-miteho-card="${CSS.escape(id)}"] .miteho-like-count`)?.textContent==='1',game.id,{timeout:30000}).catch(()=>{});return {count,visibleCount:await card.locator('.miteho-like-count').innerText()};});
  await step(b.p,'スマホその他メニュー',async()=>{await b.p.setViewportSize({width:390,height:844});await dismiss(b.p);const more=b.p.locator('[data-mobile-more]:visible').first();await more.click();const item=b.p.locator('#mobileMoreSheet [data-mobile-tab="miteho"]:visible').first();await item.waitFor();const label=(await item.innerText()).trim();await item.click();await b.p.waitForSelector('#miteHoPanel',{state:'visible'});const box=await b.p.locator('#miteHoPanel').boundingBox();if(!box||box.width>400)throw Error('スマホ幅不正');return {label,width:box.width};});
  await step(a.p,'自分の投稿を削除',async()=>{await a.p.setViewportSize({width:1360,height:900});await openMiteHo(a.p);const card=await waitCard(a.p,urlComment);const id=await card.getAttribute('data-miteho-card');await card.locator('[data-miteho-delete]').click();await a.p.waitForFunction(id=>!document.querySelector(`[data-miteho-card="${CSS.escape(id)}"]`),id,{timeout:70000});let gone=false;try{await a.p.evaluate(id=>window.fujiyaMiteMagazineApi.read(id),id);}catch{gone=true;}if(!gone)throw Error('共有DBから削除未確認');return {id,deleted:true};});
  await a.p.evaluate(ids=>{for(const id of ids){try{window.fujiyaMiteMagazineBridge.postNoWait('magazine_delete_frame',{articleId:id,userId:window.fujiyaMiteMagazineApi.currentUserId()},`cleanup_${Date.now()}_${Math.random()}`)}catch{}}},out.posts.filter(x=>x!==url.id)).catch(()=>{});
  out.finishedAt=new Date().toISOString();
  fs.writeFileSync('rc545-e2e-result.json',JSON.stringify(out,null,2));
  await a.ctx.close();await b.ctx.close();await browser.close();
}
main().catch(async e=>{out.fatal=String(e&&e.stack||e);out.finishedAt=new Date().toISOString();fs.writeFileSync('rc545-e2e-result.json',JSON.stringify(out,null,2));console.error(e);process.exit(1);});
